-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 09:54:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cella_lab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cella_lab` ;

-- -----------------------------------------------------
-- Schema cella_lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cella_lab` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `cella_lab` ;

-- -----------------------------------------------------
-- Table `community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `community` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `project_info_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `project_info`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Synthetic microbial community';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `community_formula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community_formula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `community_formula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `community_id` INT UNSIGNED NOT NULL,
  `model_id` INT UNSIGNED NOT NULL,
  `composition` DOUBLE UNSIGNED NOT NULL DEFAULT 0 COMMENT 'the microbial community composition percentage, value in range [0,1]',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `community_data_idx` (`community_id` ASC) VISIBLE,
  INDEX `standard_model_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `community_data`
    FOREIGN KEY (`community_id`)
    REFERENCES `community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `standard_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `model_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'community composition of the Synthetic microbial community';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `culture_medium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culture_medium` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `culture_medium` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dynamics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dynamics` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dynamics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `experiment_id` INT UNSIGNED NOT NULL COMMENT 'reference to the analysis experiment',
  `cella_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the model of the virtual cell GEMs',
  `molecule_id` INT UNSIGNED NOT NULL COMMENT 'the biocad registry molecule id, should be reference to the unify registry resolver table, not direct reference to the metabolites/gene/protein table',
  `x0` DOUBLE NOT NULL DEFAULT 0 COMMENT 'the initial mass content value at time zero',
  `dynamics` LONGBLOB NOT NULL COMMENT 'gzip compressed molecule mass content double[] vector, network byte order, time axis reference to a specific experiment setup',
  `mean` DOUBLE NOT NULL DEFAULT 0,
  `min` DOUBLE NOT NULL DEFAULT 0,
  `max` DOUBLE NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `experiment_project_idx` (`experiment_id` ASC) VISIBLE,
  INDEX `cell_source_idx` (`cella_id` ASC) VISIBLE,
  CONSTRAINT `cell_source`
    FOREIGN KEY (`cella_id`)
    REFERENCES `model_variant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `experiment_project`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `experiment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'cellular component dynamics data';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `experiment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `experiment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proj_id` INT UNSIGNED NOT NULL COMMENT 'the simulation experiment project id',
  `name` VARCHAR(255) NOT NULL,
  `temperature` DOUBLE NOT NULL DEFAULT 30,
  `ph` FLOAT NOT NULL DEFAULT 7.0,
  `culture_medium` INT UNSIGNED NOT NULL COMMENT 'reference to the culture_medium table',
  `total_time` DOUBLE NOT NULL DEFAULT 0,
  `time` LONGBLOB NOT NULL COMMENT 'gzip compressed network byte order encoded time points double[] vector, time axis of the dynamics data',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `project_info_idx` (`proj_id` ASC) VISIBLE,
  INDEX `culture_medium_id_idx` (`culture_medium` ASC) VISIBLE,
  CONSTRAINT `project_info`
    FOREIGN KEY (`proj_id`)
    REFERENCES `project_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `culture_medium_id`
    FOREIGN KEY (`culture_medium`)
    REFERENCES `culture_medium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'analysis experiment setup';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `model_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model_library` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `model_library` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'the cell name',
  `taxid` INT NOT NULL DEFAULT 0 COMMENT 'the ncbi taxonomy id of the cell strain',
  `metabolic_vec` JSON NOT NULL COMMENT 'metabolic annotation result, should be a vector of the enzyme annotation result data, json encode format: [ {prot_id: ec_number} ]',
  `tf_vec` JSON NOT NULL COMMENT 'a vector of the transcription regulation factor, json encode format: [ {prot_id: [ { gene_id: motif, type: activator or inhibitor, effector: [molecule1,molecule2,...]  }  ]  } ]',
  `transporter_vec` JSON NOT NULL COMMENT 'a vector of the transporter protein enzyme id',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'A library of the standard GEMs models';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `model_variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model_variant` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `model_variant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` INT UNSIGNED NOT NULL COMMENT 'reference to the GEMs model inside the standard library',
  `name` VARCHAR(255) NOT NULL COMMENT 'the model name',
  `variants` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'number of the model variants',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `standard_model_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `standard_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `model_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Variant of the standard model network';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(1024) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'cella lab project data';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `substrate_composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substrate_composition` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `substrate_composition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `culture_medium` INT UNSIGNED NOT NULL,
  `metabolite_id` INT UNSIGNED NOT NULL COMMENT 'compound molecule id reference to the registry model table in cad registry database',
  `content` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `culture_medium_info_idx` (`culture_medium` ASC) VISIBLE,
  CONSTRAINT `culture_medium_info`
    FOREIGN KEY (`culture_medium`)
    REFERENCES `culture_medium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Substrate composition of the Culture medium composition';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `substrate_modification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substrate_modification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `substrate_modification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `experiment_id` INT UNSIGNED NOT NULL,
  `metabolite_id` INT UNSIGNED NOT NULL COMMENT 'compound molecule id reference to the registry model table in cad registry database',
  `content` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `experiment_info_idx` (`experiment_id` ASC) VISIBLE,
  CONSTRAINT `experiment_info`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `experiment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'modification of the culture_medium';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `variants` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `variants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `variant_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NOT NULL COMMENT 'the type of the modification, example as gene expression level, enzyme kinetics parameter, etc',
  `object_id` VARCHAR(45) NOT NULL COMMENT 'object inside the standard GEMs model',
  `parameters` JSON NULL COMMENT 'the Variant parameter of the target object',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `model_source_idx` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `model_source`
    FOREIGN KEY (`variant_id`)
    REFERENCES `model_variant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Variants details of the model';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
