-- MySQL Script generated by MySQL Workbench
-- Tue Mar 17 17:48:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cella_lab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cella_lab` ;

-- -----------------------------------------------------
-- Schema cella_lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cella_lab` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `cella_lab` ;

-- -----------------------------------------------------
-- Table `community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `community` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Synthetic microbial community';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `community` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `project_info_idx` ON `community` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `community_formula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community_formula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `community_formula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `community_id` INT UNSIGNED NOT NULL,
  `model_id` INT UNSIGNED NOT NULL,
  `composition` DOUBLE UNSIGNED NOT NULL DEFAULT 0 COMMENT 'the microbial community composition percentage, value in range [0,1]',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'community composition of the Synthetic microbial community';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `community_formula` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `community_data_idx` ON `community_formula` (`community_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `standard_model_idx` ON `community_formula` (`model_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `culture_medium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culture_medium` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `culture_medium` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `culture_medium` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dynamics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dynamics` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dynamics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `experiment_id` INT UNSIGNED NOT NULL COMMENT 'reference to the analysis experiment',
  `cella_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the model of the virtual cell GEMs',
  `molecule_id` INT UNSIGNED NOT NULL COMMENT 'the biocad registry molecule id, should be reference to the unify registry resolver table, not direct reference to the metabolites/gene/protein table',
  `x0` DOUBLE NOT NULL DEFAULT 0 COMMENT 'the initial mass content value at time zero',
  `dynamics` LONGTEXT NOT NULL COMMENT 'gzip compressed based 64 encoded molecule mass content double[] vector, time axis reference to a specific experiment setup',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'cellular component dynamics data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `dynamics` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `experiment_project_idx` ON `dynamics` (`experiment_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `cell_source_idx` ON `dynamics` (`cella_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `experiment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `experiment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proj_id` INT UNSIGNED NOT NULL COMMENT 'the simulation experiment project id',
  `name` VARCHAR(255) NOT NULL,
  `temperature` DOUBLE NOT NULL DEFAULT 30,
  `culture_medium` INT UNSIGNED NOT NULL COMMENT 'reference to the culture_medium table',
  `total_time` DOUBLE NOT NULL DEFAULT 0,
  `time` LONGTEXT NOT NULL COMMENT 'gzip compressed based 64 encoded time points double[] vector, time axis of the dynamics data',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'analysis experiment setup';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `experiment` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `project_info_idx` ON `experiment` (`proj_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `culture_medium_id_idx` ON `experiment` (`culture_medium` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `model_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model_library` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `model_library` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'the cell name',
  `taxid` INT NOT NULL DEFAULT 0 COMMENT 'the ncbi taxonomy id of the cell strain',
  `metabolic_vec` JSON NOT NULL COMMENT 'metabolic annotation result, should be a vector of the enzyme annotation result data, json encode format: [ {prot_id: ec_number} ]',
  `tf_vec` JSON NOT NULL COMMENT 'a vector of the transcription regulation factor, json encode format: [ {prot_id: [ { gene_id: motif, type: activator or inhibitor, effector: [molecule1,molecule2,...]  }  ]  } ]',
  `transporter_vec` JSON NOT NULL COMMENT 'a vector of the transporter protein enzyme id',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'A library of the standard GEMs models';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `model_library` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `model_variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `model_variant` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `model_variant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` INT UNSIGNED NOT NULL COMMENT 'reference to the GEMs model inside the standard library',
  `name` VARCHAR(255) NOT NULL COMMENT 'the model name',
  `variants` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'number of the model variants',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Variant of the standard model network';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `model_variant` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `standard_model_idx` ON `model_variant` (`model_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(1024) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'cella lab project data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `project_data` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `project_id_UNIQUE` ON `project_data` (`project_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `substrate_composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substrate_composition` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `substrate_composition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `culture_medium` INT UNSIGNED NOT NULL,
  `metabolite_id` INT UNSIGNED NOT NULL,
  `content` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Substrate composition of the Culture medium composition';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `substrate_composition` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `culture_medium_info_idx` ON `substrate_composition` (`culture_medium` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `substrate_modification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substrate_modification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `substrate_modification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `experiment_id` INT UNSIGNED NOT NULL,
  `metabolite_id` INT UNSIGNED NOT NULL,
  `content` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'modification of the culture_medium';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `substrate_modification` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `experiment_info_idx` ON `substrate_modification` (`experiment_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `variants` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `variants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `variant_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NOT NULL COMMENT 'the type of the modification, example as gene expression level, enzyme kinetics parameter, etc',
  `object_id` VARCHAR(45) NOT NULL COMMENT 'object inside the standard GEMs model',
  `parameters` JSON NULL COMMENT 'the Variant parameter of the target object',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Variants details of the model';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `variants` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `model_source_idx` ON `variants` (`variant_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
